extends:
  - stylelint-config-standard
  # Disable any conflicting formatting rules, and run Prettier for the (part of
  # the) files that the linter has found to be stylesheets:
  - stylelint-prettier/recommended
